### ISSUE TITLE
Chat window surface color doesn't respect light/dark theme

### ISSUE THREAD

**Issue by dgmltn** [pubnub/chat-components-android-examples#5]
<img width="932" alt="light-dark-mode" src="https://user-images.githubusercontent.com/698270/161345555-cf935dd9-b751-452e-b262-41eb0b853fd6.png">

**Comment by Chesteer89** [comment]
Hi!
Thanks for your contribution. Please take a look at the comment about the used color in the PR.

I would also like to inform you that we are working on the default appearance of the components that will fix this issue.
