### ISSUE TITLE
New messages aren't received until app launch

### ISSUE THREAD

**Issue by dgmltn** [pubnub/chat-components-android-examples#7]
Not sure what's going on here, but new messages sent from other devices aren't received until the app is first launched. They're all added, and the list catches up (when the app is first launched). After that, messages sent from other devices don't pop in when they're sent. The Debug Console shows messages being sent properly.

**Comment by Chesteer89** [comment]
Please check your PubNub key settings in [Admin portal](https://admin.pubnub.com/).
To receive historical messages `MESSAGE PERSISTENCE` option should be turned on.

**Comment by Chesteer89** [comment]
The problem was related to missing `ChannelId` parameter in `AddDummyData()` (not passed in ChatActivity)

Fix available in: #8
